### ISSUE TITLE
请问，这个库能实现以下几种样式吗？

### ISSUE THREAD

**Issue by kazeik** [alivebao/FreeSizeDraggableLayout#2]
样式如： |        |    2  |
               |    1   |     3  | 
               |         |        |
我解释一下吧，有 1，2，3倍大小的View , 就是左边排1个3倍大的view，右边排三个1倍大小的view， 或者左边排一个2倍大小的View，右边排两个1倍大小的View. 或者左边排一个2倍大小和1倍大小的view，右边排一个3倍大小的View .或者左右各排一个1倍大小的view。这几个View在最外围宽高度上相等。
有点类似于Vlayout。但Vlayout只能右边排两个。

**Comment by alivebao** [comment]
你可以看看readme里的动图是否符合你的需求，或者把代码下下来修改成你需要的布局(调整一下UnitWidth/HeightNum)。
我没理解错的话是支持的，大小相等的view就可以互相移动位置:-)
